name: Publish Testing Package
on:
  push:
    branches:
      - "staging/**"
jobs:
  publish:
    name: Package Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Package
        run: dotnet pack --no-restore -o .
      - name: Publish to Nuget
        env:
          NUGET_KEY: ${{ secrets.DEPLOY_TEST_KEY }}
          NUGET_API: https://apiint.nugettest.org/v3/index.json
        run: dotnet nuget push CSTNet.*.nupkg --api-key $NUGET_KEY --source $NUGET_API
